format = """
$username\
$hostname\
$os
$directory $character"""



# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'




# Inserts a blank line between shell prompts
add_newline = false

[character]
success_symbol = '[ ](#393939)'
error_symbol = '[ ](#393939)' 




[custom.arch]
command = 'echo'
format = ' arch linux'

[directory]
disabled = false
style = '#393939'
format = '($style)[$path]($style)'


[fill]
symbol = " "
